web:
    restart: always
    build: ./web
    volumes:
        - web:/code
    ports:
        - "5000:5000"
    links:
        - redis
    env_file: .env
redis:
    image: redis
    ports:
        - "6379:6379"
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
